### ISSUE TITLE
代码运行报错

### ISSUE THREAD

**Issue by shuqincao** [LiuZH-19/Ada-STNet#1]
utils里面的” for x, y in tqdm(data_loaders[phase], f'{phase.capitalize():5} {epoch}'):“
这一行报错：Invalid argument

**Comment by LiuZH-19** [comment]
我重新跑了代码，并没有报错。你或许可以更详细地描述一下你报错的场景。

**Comment by shuqincao** [comment]
Train 0:   0%|          | 0/375 [00:00<?, ?it/s]Traceback (most recent call last):
  File "F:/orginalCode/Ada-STNet-master/train_stage1.py", line 93, in <module>
    train(config)
  File "F:/orginalCode/Ada-STNet-master/train_stage1.py", line 61, in train
    early_stop_steps=config['early_stop_steps']
  File "F:\orginalCode\Ada-STNet-master\utils\utils.py", line 122, in train_model
    for x, y in tqdm(data_loaders[phase], f'{phase.capitalize():5} {epoch}'):
  File "D:\programfiles\Anaconda3\lib\site-packages\tqdm\std.py", line 1107, in __iter__
    for obj in iterable:
  File "D:\programfiles\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "D:\programfiles\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\programfiles\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()
  File "D:\programfiles\Anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "D:\programfiles\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\programfiles\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\programfiles\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\programfiles\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
OSError: [Errno 22] Invalid argument
Train 0:   0%|          | 0/375 [00:07<?, ?it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\programfiles\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\programfiles\Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated

**Comment by shuqincao** [comment]
在运行train_stage1.py时，运行到utils.py的第122行“                for x, y in tqdm(data_loaders[phase], f'{phase.capitalize():5} {epoch}'):
” 就报错， 请问你的tqdm用的什么版本呢？

**Comment by LiuZH-19** [comment]
tqdm的版本为4.62.3。可能数据集保存过程中出现数据损失，重新下载新的数据集再次测试一下吧。

**Comment by SongDrink** [comment]
我也遇到了相同的问题，数据集反复下载了也没有解决。

Traceback (most recent call last):
  File "F:/program/Ada-STNet-master/Ada-STNet-master/train_stage1.py", line 93, in <module>
    train(config)
  File "F:/program/Ada-STNet-master/Ada-STNet-master/train_stage1.py", line 54, in train
    utils.train_model(
  File "F:\program\Ada-STNet-master\Ada-STNet-master\utils\utils.py", line 123, in train_model
    for x, y in tqdm(data_loaders[phase]):
  File "F:\program\miniconda\lib\site-packages\tqdm\std.py", line 1180, in __iter__
    for obj in iterable:
  File "F:\program\miniconda\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "F:\program\miniconda\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "F:\program\miniconda\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "F:\program\miniconda\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "F:\program\miniconda\lib\multiprocessing\context.py", line 326, in _Popen
    return Popen(process_obj)
  File "F:\program\miniconda\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "F:\program\miniconda\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
OSError: [Errno 22] Invalid argument
